


development:
  adapter: postgresql
  encoding: unicode
  database: motiposters_development
  host: localhost
  pool: 5
# NOT TIM??? THEN TRY THIS:
  # username: 
  # password: 
  username: postgres
  password: <%= ENV["PG_PASS"] %>


test:
  adapter: postgresql
  encoding: unicode
  database: motiposters_test
  host: localhost
  pool: 5
# NOT TIM??? THEN TRY THIS:
  # username: 
  # password: 
  username: postgres
  password: <%= ENV["PG_PASS"] %>
