development:
  adapter: postgresql
  encoding: unicode
  database: motiposters_development
  host: localhost
  pool: 5
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>


test:
  adapter: postgresql
  encoding: unicode
  database: motiposters_test
  host: localhost
  pool: 5
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>